# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
#permalink:        pretty

# Setup
title:            ISME
tagline:          '修和无人见，存心有天知'
description:      'Just for fun !'
url:              http://c3porobot.com

author:
  name:           'ISME'
  url:            https://github.com/alertisme

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : 
#    duoshuo :
#     short_name : isme
